
ACTION KOM_VentilovyTerminal: 

	//Mapovanie ventilového terminálu VT1//
	
//	Linka.OUT.VT1_PowerlinkOUTPUTS[0].0; 
//	Linka.OUT.VT1_PowerlinkOUTPUTS[0].1;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[0].2:= VstupVytah.OUT.DvereVytahu_ZATVOR_YV001; 
//	Linka.OUT.VT1_PowerlinkOUTPUTS[0].3:= VstupVytah.OUT.DvereVytahu_OTVOR_YV002;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[0].4;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[0].5; 
//	Linka.OUT.VT1_PowerlinkOUTPUTS[0].6:= StoperEtiketovania.OUT.Centrovanie_VYSUN_YV003; 
//	Linka.OUT.VT1_PowerlinkOUTPUTS[0].7:= StoperEtiketovania.OUT.Centrovanie_ZASUN_YV004;
//	
//	
//	Linka.OUT.VT1_PowerlinkOUTPUTS[1].0:= StoperPredCistenim.OUT.StoperZASUN_YV005;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[1].1:= StoperPoCisteni.OUT.StoperZASUN_YV006;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[1].2:= StoperEtiketovania.OUT.StoperZASUN_YV007;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[1].3:= StoperDopravNG.OUT.NatlakujTlmicPaletky_YV008;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[1].4:= StoperDopravNG.OUT.Centrovanie_VYSUN_YV009;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[1].5:= StoperDopravNG.OUT.Centrovanie_ZASUN_YV010;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[1].6:= StoperVystupDopravnika.OUT.StoperZASUN_YV011;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[1].7:= StoperVratDopravnika.OUT.StoperZASUN_YV012;
//	
//	
//	Linka.OUT.VT1_PowerlinkOUTPUTS[2].0;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[2].1; 
//	Linka.OUT.VT1_PowerlinkOUTPUTS[2].2:= Robot.OUT.PrisavanieEtikety_ZAPNI_YV013; 
//	Linka.OUT.VT1_PowerlinkOUTPUTS[2].3:= Robot.OUT.PrisavanieEtikety_VYPNI_YV014;
//	Linka.OUT.VT1_PowerlinkOUTPUTS[2].4; 
//	Linka.OUT.VT1_PowerlinkOUTPUTS[2].5; 
//	Linka.OUT.VT1_PowerlinkOUTPUTS[2].6; 
//	Linka.OUT.VT1_PowerlinkOUTPUTS[2].7; 
	
	
	
END_ACTION
